### PR TITLE
fix(node-disk-manager): support nvme virtual paths

### LINKED ISSUE #675: NVME mount points not being recognized on OpenSUSE 15.3
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and the sequence of operations performed / commands you ran.]
I have NVME disks, and they are not being detected properly for filtering out mount points.  The issue is in the
`getParentBlockDevice()` routine at [getParentBlockDevice](https://github.com/openebs/node-disk-manager/blob/develop/pkg/mount/mountutil.go#L238-L271)

The code is looking for a `/nvme/` component, like in the given example of:
```
/sys/devices/pci0000:00/0000:00:0e.0/nvme/nvme0/nvme0n1/nvme0n1p1
```

However, on my OpenSUSE 15.2 and 15.3 systems, the paths are different, for example from the NDM logs:
```
E0707 17:40:05.246852       7 osdiskexcludefilter.go:92] unable to configure os disk filter for mountpoint: /mnt/openebs-local, error: could not find parent device for /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1/nvme0n1p1
```
There is a directory for each NVME disk, not just a single `/nvme/` directory:
```
# ls /sys/devices/virtual/nvme-subsystem
nvme-subsys0  nvme-subsys1  nvme-subsys2  nvme-subsys3  nvme-subsys4
```

**What did you expect to happen:**
The NVME code needs to be expanded to handle `/nvme-subsysX/` in addition to just `/nvme/`

**Environment:**
- OpenEBS version: 3.2 (NDM 1.9.0)
- Kubernetes version (use `kubectl version`): 1.20.15
- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: baremetal
- Type of disks connected to the nodes: NVME
- OS (e.g. from `/etc/os-release`): openSUSE Leap 15.3

### PR DESCRIPTION
**Pull request by dborman-hpe**
Enhance getParentBlockDevice() by looking not only
for /nvme/ in the path, but also /nvme-subystem/,
which is the name under /sys/devices/virtual on
OpenSUSE 15.3.

Also clean up the osdiskexcludefilter.go Start()
routine so that for each mount point it will first
check /proc/1/mounts and if that fails, then check
/proc/self/mounts, and then if that also fails, finally
log an error message.  The observation is that things
will be found in one or the other, but not both, so
the old code would print out an error message in one
case, even when the mountpoint had been added to the
filter list by the other case.

Signed-off-by: David Borman <77121405+dborman-hpe@users.noreply.github.com>

## Pull Request template

**Why is this PR required? What issue does it fix?**:
NDM failed to filter out nvme disks on OpenSUSE 15.3 due a difference in the path name

**What this PR does?**:
Adds looking for `nvme-subsystem` in addition to `nvme`

**Does this PR require any upgrade changes?**:
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
I have one mount point to be filtered out, `/mnt/openebs-local` which is mounted on `/dev/nvme0n1p1`
I looked at the logs, and now see lines like:
```
I0812 17:54:15.820739       7 osdiskexcludefilter.go:131] applying os-filter regex ^/dev/nvme0n1(p[0-9]+)?$ on /dev/nvme2n1
```
whereas before it didn't have that regex filter.

For the logs on creating the filters, it now has:
```
E0812 17:54:15.695414       7 osdiskexcludefilter.go:108] unable to configure os disk filter for mountpoint: /boot, error: could not get device mount attributes, Path/MountPoint not present in mounts file
E0812 17:54:15.697012       7 osdiskexcludefilter.go:108] unable to configure os disk filter for mountpoint: /var/lib/etcd, error: could not get device mount attributes, Path/MountPoint not present in mounts file
```
whereas before it had:
```
E0707 17:40:05.246362       7 osdiskexcludefilter.go:92] unable to configure os disk filter for mountpoint: /etc/hosts, error: could not get device mount attributes, Path/MountPoint not present in mounts file
E0707 17:40:05.246588       7 osdiskexcludefilter.go:92] unable to configure os disk filter for mountpoint: /boot, error: could not get device mount attributes, Path/MountPoint not present in mounts file
E0707 17:40:05.246852       7 osdiskexcludefilter.go:92] unable to configure os disk filter for mountpoint: /mnt/openebs-local, error: could not find parent device for /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1/nvme0n1p1
E0707 17:40:05.247076       7 osdiskexcludefilter.go:92] unable to configure os disk filter for mountpoint: /var/lib/etcd, error: could not get device mount attributes, Path/MountPoint not present in mounts file
E0707 17:40:05.247203       7 osdiskexcludefilter.go:104] unable to configure os disk filter for mountpoint: /, error: could not get device mount attributes, Path/MountPoint not present in mounts file
E0707 17:40:05.247429       7 osdiskexcludefilter.go:104] unable to configure os disk filter for mountpoint: /boot, error: could not get device mount attributes, Path/MountPoint not present in mounts file
E0707 17:40:05.247522       7 osdiskexcludefilter.go:104] unable to configure os disk filter for mountpoint: /mnt/openebs-local, error: could not get device mount attributes, Path/MountPoint not present in mounts file
E0707 17:40:05.247612       7 osdiskexcludefilter.go:104] unable to configure os disk filter for mountpoint: /var/lib/etcd, error: could not get device mount attributes, Path/MountPoint not present in mounts file
```

**Any additional information for your reviewer?** : 
No

**Checklist:**
- [x] Fixes #675
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [x] Has the change log section been updated? N/A - minor bugfix
- [x] Commit has unit tests
- [x] Commit has integration tests - N/A

### CODE REVIEW

**Comment by dborman-hpe** [comment]
There was one more place where it was only looking for `nvme`, in `pkg/sysfs/syspath.go`, hence the force-push to fix that other location.  With that additional change I am no longer seeing partitions of the main device getting block devices created.  From the logs:
```
addhandler.go:193] parent device: /dev/nvme1n1 is in use, device: /dev/nvme1n1p9 can be ignored
```

File: pkg/mount/mountutil.go [hunk 1]
```diff
@@ -240,13 +240,18 @@ func parseRootDeviceLink(file io.Reader) (string, error) {
...
+//     /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1/nvme0n1p1
+// So we search for the "nvme" or "nvme-subsystem" subsystem instead of `block`. The
+// blockdevice will be available after the NVMe instance,
+//     nvme/instance/namespace
+//     nvme-subsystem/instance/namespace
 // The namespace will be the blockdevice.
 func getParentBlockDevice(sysPath string) (string, bool) {
 	blockSubsystem := "block"
 	nvmeSubsystem := "nvme"
+	altNvmeSubsystem := "nvme-subsystem"
```
Comment (akhilerm) [inline pkg/mount/mountutil.go]: Can you use a different variable name for this. May be check what is used in the kernel and name accordingly.?

File: pkg/sysfs/syspath.go [hunk 2]
```diff
@@ -86,7 +87,7 @@ func (s Device) getParent() (string, bool) {
 	// nvme namespace. Length checking is to avoid index out of range in case of malformed
 	// links (extremely rare case)
 	for i, part := range parts {
-		if part == NVMeSubSystem {
+		if part == NVMeSubSystem || part == altNVMeSubSystem {
```
Comment (akhilerm) [inline pkg/sysfs/syspath.go]: Add test cases for this change [here](https://github.com/openebs/node-disk-manager/blob/develop/pkg/sysfs/syspath_test.go#L29)

File: pkg/mount/mountutil.go [hunk 3]
```diff
@@ -240,13 +240,18 @@ func parseRootDeviceLink(file io.Reader) (string, error) {
...
-// instead of `block`. The blockdevice will be available after the NVMe instance, nvme/instance/namespace.
+// for blockdevices that belong to the nvme subsystem, the symlink has different formats
+//     /sys/devices/pci0000:00/0000:00:0e.0/nvme/nvme0/nvme0n1/nvme0n1p1.
+//     /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1/nvme0n1p1
+// So we search for the "nvme" or "nvme-subsystem" subsystem instead of `block`. The
+// blockdevice will be available after the NVMe instance,
+//     nvme/instance/namespace
+//     nvme-subsystem/instance/namespace
 // The namespace will be the blockdevice.
 func getParentBlockDevice(sysPath string) (string, bool) {
```
Comment (akhilerm) [inline pkg/mount/mountutil.go:251]: Please add new tests to cover the new cases [here](https://github.com/openebs/node-disk-manager/blob/develop/pkg/mount/mountutil_test.go#L268)

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go [hunk 4]
```diff
@@ -80,33 +80,31 @@ func newNonOsDiskFilter(ctrl *controller.Controller) *oSDiskExcludeFilter {
...
-		disk's path of it adds it in Controller struct and make isOsDiskFilterSet true
-	*/
-	for _, mountPoint := range mountPoints {
-		mountPointUtil := mount.NewMountUtil(defaultMountFilePath, "", mountPoint)
-		if devPath, err := mountPointUtil.GetDiskPath(); err != nil {
-			klog.Errorf("unable to configure os disk filter for mountpoint: %s, error: %v", mountPoint, err)
-		} else {
+
+		// process2 check for mountpoints in /proc/self/mounts file if it is able to get
+		// disk's path of it adds it in Controller struct and make isOsDiskFilterSet true
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter.go]: Can you modify the comment, because I dont think we are using the `isOsDiskFilterSet` variable anymore

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go [hunk 5]
```diff
@@ -80,33 +80,31 @@ func newNonOsDiskFilter(ctrl *controller.Controller) *oSDiskExcludeFilter {
...
+		// host's /proc/1/mounts file mounted inside container it checks for
+		// every mentioned mountpoints if it is able to get parent disk's devpath
+		// it adds it in Controller struct and make isOsDiskFilterSet true
 		mountPointUtil := mount.NewMountUtil(hostMountFilePath, "", mountPoint)
-		if devPath, err := mountPointUtil.GetDiskPath(); err != nil {
-			klog.Errorf("unable to configure os disk filter for mountpoint: %s, error: %v", mountPoint, err)
-		} else {
+		if devPath, err = mountPointUtil.GetDiskPath(); err == nil {
 			odf.excludeDevPaths = append(odf.excludeDevPaths, devPath)
+			continue
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter.go:97]: Thanks for making this change. Now we will have less unwanted error messages.

**Review by akhilerm — CHANGES_REQUESTED** [review]
A few questions on the change and test cases need to be added.

File: pkg/mount/mountutil.go (hunk 1 above)
Comment (dborman-hpe) [reply pkg/mount/mountutil.go]: Looking through the kernel, the only reference is:
```
drivers/nvme/host/core.c:	nvme_subsys_class = class_create(THIS_MODULE, "nvme-subsystem");
```
so I'll change it to `nvmeSubsysClass`.  I'm open to other suggestions, the variable name doesn't matter much to me.

File: pkg/sysfs/syspath.go (hunk 2 above)
Comment (dborman-hpe) [reply pkg/sysfs/syspath.go]: Done.

File: pkg/mount/mountutil.go (hunk 3 above)
Comment (dborman-hpe) [reply pkg/mount/mountutil.go:251]: Done.

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go (hunk 4 above)
Comment (dborman-hpe) [reply cmd/ndm_daemonset/filter/osdiskexcludefilter.go]: Done.

**Comment by dborman-hpe** [comment]
Thanks for the review @akhilerm.  I think I have addressed all your comments.  In addition, I made a fix for `make test` so that it will run all the go tests and not stop at the first failure.  The system where I am building has only NVMe disks, so some of the tests that assume there is a local `/dev/sda` fail.  But for the tests I modified:
```
ok  	github.com/openebs/node-disk-manager/pkg/mount	0.008s	coverage: 84.3% of statements
ok  	github.com/openebs/node-disk-manager/pkg/mount/libmount	0.005s	coverage: 45.7% of statements
ok  	github.com/openebs/node-disk-manager/pkg/sysfs	0.016s	coverage: 88.7% of statements
```

If you are happy with these changes, I will squash things back down to a single commit.

**Review by akhilerm — APPROVED** [review]
LGTM

On another note: which are the tests that fail if you have only NVMe disks on your machine? My assumption was that we were not directly looking for a `/dev/sda` to be present on the system for the tests to run.

**Comment by dborman-hpe** [comment]
> LGTM
> 
> On another note: which are the tests that fail if you have only NVMe disks on your machine? My assumption was that we were not directly looking for a `/dev/sda` to be present on the system for the tests to run.

Here's the output I get from `make test`:
```
# make test
go list ./... | grep -v "./vendor/*" | xargs go vet -composites
find . -type f -name "*.go" | grep -v "./vendor/*" | xargs gofmt -s -w -l
./pkg/sysfs/syspath.go
--> Running go test
/root/ndm/node-disk-manager/build/test.sh amd64
?   	github.com/openebs/node-disk-manager/api/v1alpha1	[no test files]
?   	github.com/openebs/node-disk-manager/api-service/node	[no test files]
I0824 21:04:02.269145  415835 listBlockDeviceDetails.go:30] Listing Device Details
E0824 21:04:02.269237  415835 listBlockDeviceDetails.go:37] Error fetching block device details map[DetectScsiTypeError:no such file or directory]
I0824 21:04:02.269288  415835 listBlockDeviceDetails_test.go:40] <nil>
--- FAIL: TestListBlockDeviceDetails (0.00s)
    listBlockDeviceDetails_test.go:38: Error listing details rpc error: code = Internal desc = Error fetching disk details
I0824 21:04:02.269378  415835 nodeName.go:31] Node name is : TEST_NODE
FAIL
coverage: 10.0% of statements
FAIL	github.com/openebs/node-disk-manager/api-service/node/services	0.024s
FAIL
?   	github.com/openebs/node-disk-manager/blockdevice	[no test files]
?   	github.com/openebs/node-disk-manager/cmd/manager	[no test files]
?   	github.com/openebs/node-disk-manager/cmd/ndm-exporter	[no test files]
?   	github.com/openebs/node-disk-manager/cmd/ndm-exporter/cmd	[no test files]
?   	github.com/openebs/node-disk-manager/cmd/ndm_daemonset	[no test files]
?   	github.com/openebs/node-disk-manager/cmd/ndm_daemonset/app	[no test files]
?   	github.com/openebs/node-disk-manager/cmd/ndm_daemonset/app/command	[no test files]
ok  	github.com/openebs/node-disk-manager/cmd/ndm_daemonset/controller	0.032s	coverage: 59.5% of statements
ok  	github.com/openebs/node-disk-manager/cmd/ndm_daemonset/filter	0.025s	coverage: 72.5% of statements
?   	github.com/openebs/node-disk-manager/cmd/ndm_daemonset/grpc	[no test files]
I0824 21:04:15.277355  421580 uuid.go:78] device(/dev/sdX) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.277450  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sdX
I0824 21:04:15.277457  421580 uuid.go:78] device(/dev/sdZ) has a WWN, using WWN: fake-WWN and Serial: 
I0824 21:04:15.277462  421580 uuid.go:101] generated uuid: blockdevice-7790348f6b96db34aa2a5e5f37b7cb2e for device: /dev/sdZ
I0824 21:04:15.277918  421580 addhandler.go:376] device: /dev/sda1 in use by zfs-localPV
I0824 21:04:15.277992  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-e3701993bc59b10abb6b331a385dfff3
I0824 21:04:15.278002  421580 addhandler.go:399] Pushed zfs-localPV device: blockdevice-e3701993bc59b10abb6b331a385dfff3 (/dev/sda1) to etcd
I0824 21:04:15.279478  421580 addhandler.go:376] device: /dev/sda in use by zfs-localPV
I0824 21:04:15.279523  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-e3701993bc59b10abb6b331a385dfff3
I0824 21:04:15.279532  421580 addhandler.go:399] Pushed zfs-localPV device: blockdevice-e3701993bc59b10abb6b331a385dfff3 (/dev/sda) to etcd
I0824 21:04:15.279631  421580 addhandler.go:376] device: /dev/sda in use by zfs-localPV
I0824 21:04:15.279745  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-e3701993bc59b10abb6b331a385dfff3
I0824 21:04:15.279754  421580 addhandler.go:399] Pushed zfs-localPV device: blockdevice-e3701993bc59b10abb6b331a385dfff3 (/dev/sda) to etcd
I0824 21:04:15.280145  421580 addhandler.go:376] device: /dev/sda in use by zfs-localPV
I0824 21:04:15.280179  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-e3701993bc59b10abb6b331a385dfff3
I0824 21:04:15.280188  421580 addhandler.go:399] Pushed zfs-localPV device: blockdevice-e3701993bc59b10abb6b331a385dfff3 (/dev/sda) to etcd
I0824 21:04:15.280313  421580 addhandler.go:376] device: /dev/sda1 in use by zfs-localPV
I0824 21:04:15.280339  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-e3701993bc59b10abb6b331a385dfff3
I0824 21:04:15.280348  421580 addhandler.go:399] Pushed zfs-localPV device: blockdevice-e3701993bc59b10abb6b331a385dfff3 (/dev/sda1) to etcd
I0824 21:04:15.280466  421580 addhandler.go:376] device: /dev/sda in use by zfs-localPV
I0824 21:04:15.280549  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-e3701993bc59b10abb6b331a385dfff3
I0824 21:04:15.280558  421580 addhandler.go:399] Pushed zfs-localPV device: blockdevice-e3701993bc59b10abb6b331a385dfff3 (/dev/sda) to etcd
I0824 21:04:15.281795  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.281946  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-123
I0824 21:04:15.282062  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.282072  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.282162  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.282170  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
E0824 21:04:15.282177  421580 addhandler.go:415] unreachable state
I0824 21:04:15.282247  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.282256  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.282284  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-92801bf27615645d9ce40df12698fb63
I0824 21:04:15.282291  421580 addhandler.go:594] Pushed cstor device: blockdevice-92801bf27615645d9ce40df12698fb63 (/dev/sda) to etcd
I0824 21:04:15.282429  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.282438  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.282467  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.282474  421580 addhandler.go:594] Pushed cstor device: blockdevice-123 (/dev/sda) to etcd
I0824 21:04:15.282576  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.282585  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.282610  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-92801bf27615645d9ce40df12698fb63
I0824 21:04:15.282618  421580 addhandler.go:594] Pushed cstor device: blockdevice-92801bf27615645d9ce40df12698fb63 (/dev/sda) to etcd
I0824 21:04:15.282782  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.282791  421580 addhandler.go:594] Pushed cstor device: blockdevice-123 (/dev/sda) to etcd
I0824 21:04:15.282926  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.282936  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
E0824 21:04:15.282943  421580 addhandler.go:454] unreachable state
I0824 21:04:15.283022  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.283030  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.283057  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.283063  421580 addhandler.go:594] Pushed cstor device: blockdevice-123 (/dev/sda) to etcd
I0824 21:04:15.283187  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.283195  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.283271  421580 uuid.go:73] device(/dev/sda1) is a partition, using partition UUID: fake-part-entry-1
I0824 21:04:15.283279  421580 uuid.go:101] generated uuid: blockdevice-59f4910ce3f1c54900704528c2ce63eb for device: /dev/sda1
I0824 21:04:15.283382  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.283390  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.283418  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.283425  421580 addhandler.go:594] Pushed cstor device: blockdevice-123 (/dev/sda) to etcd
I0824 21:04:15.283568  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-e56534a0813e85c645078aa63c6aa717
I0824 21:04:15.283576  421580 addhandler.go:594] Pushed cstor device: blockdevice-e56534a0813e85c645078aa63c6aa717 (/dev/sda) to etcd
I0824 21:04:15.283662  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.283671  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.283756  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.283764  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.283832  421580 uuid.go:73] device(/dev/sda1) is a partition, using partition UUID: fake-part-entry-1
I0824 21:04:15.283839  421580 uuid.go:101] generated uuid: blockdevice-59f4910ce3f1c54900704528c2ce63eb for device: /dev/sda1
I0824 21:04:15.283906  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.283914  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
E0824 21:04:15.283922  421580 addhandler.go:471] unreachable state
I0824 21:04:15.283998  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.284008  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.284054  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.284062  421580 addhandler.go:578] Pushed localPV device: blockdevice-123 (/dev/sda) to etcd
I0824 21:04:15.284234  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-e56534a0813e85c645078aa63c6aa717
I0824 21:04:15.284242  421580 addhandler.go:578] Pushed localPV device: blockdevice-e56534a0813e85c645078aa63c6aa717 (/dev/sda) to etcd
I0824 21:04:15.284391  421580 uuid.go:85] device(/dev/sda) has a filesystem, using filesystem UUID: fake-fs-uuid
I0824 21:04:15.284400  421580 uuid.go:101] generated uuid: blockdevice-fa162d8841af6a7c1be3615bdd1e53f4 for device: /dev/sda
I0824 21:04:15.284427  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.284434  421580 addhandler.go:578] Pushed localPV device: blockdevice-123 (/dev/sda) to etcd
I0824 21:04:15.284555  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.284564  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.284590  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-92801bf27615645d9ce40df12698fb63
I0824 21:04:15.284597  421580 addhandler.go:578] Pushed localPV device: blockdevice-92801bf27615645d9ce40df12698fb63 (/dev/sda) to etcd
I0824 21:04:15.284697  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.284705  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.284730  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-92801bf27615645d9ce40df12698fb63
I0824 21:04:15.284736  421580 addhandler.go:578] Pushed localPV device: blockdevice-92801bf27615645d9ce40df12698fb63 (/dev/sda) to etcd
I0824 21:04:15.284892  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.284901  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.284927  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.284933  421580 addhandler.go:578] Pushed localPV device: blockdevice-123 (/dev/sda) to etcd
I0824 21:04:15.285059  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.285068  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
E0824 21:04:15.285076  421580 addhandler.go:512] unreachable state
I0824 21:04:15.285161  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.285170  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.285195  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.285202  421580 addhandler.go:578] Pushed localPV device: blockdevice-123 (/dev/sda) to etcd
I0824 21:04:15.285351  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.285360  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.285390  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-92801bf27615645d9ce40df12698fb63
I0824 21:04:15.285397  421580 addhandler.go:578] Pushed localPV device: blockdevice-92801bf27615645d9ce40df12698fb63 (/dev/sda) to etcd
I0824 21:04:15.285536  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.285545  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
E0824 21:04:15.285553  421580 addhandler.go:454] unreachable state
I0824 21:04:15.285620  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.285628  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
E0824 21:04:15.285635  421580 addhandler.go:512] unreachable state
I0824 21:04:15.285765  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.285774  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.285803  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-92801bf27615645d9ce40df12698fb63
I0824 21:04:15.285810  421580 addhandler.go:594] Pushed cstor device: blockdevice-92801bf27615645d9ce40df12698fb63 (/dev/sda) to etcd
I0824 21:04:15.285896  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.285904  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.285911  421580 uuid.go:73] device() is a partition, using partition UUID: fake-part-entry-1
I0824 21:04:15.285916  421580 uuid.go:101] generated uuid: blockdevice-59f4910ce3f1c54900704528c2ce63eb for device: 
I0824 21:04:15.285980  421580 addhandler.go:376] device: /dev/sda in use by zfs-localPV
I0824 21:04:15.285996  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-e3701993bc59b10abb6b331a385dfff3
I0824 21:04:15.286004  421580 addhandler.go:399] Pushed zfs-localPV device: blockdevice-e3701993bc59b10abb6b331a385dfff3 (/dev/sda) to etcd
I0824 21:04:15.286128  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.286137  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.286155  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-92801bf27615645d9ce40df12698fb63
I0824 21:04:15.286160  421580 addhandler.go:594] Pushed cstor device: blockdevice-92801bf27615645d9ce40df12698fb63 (/dev/sda) to etcd
I0824 21:04:15.286284  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.286529  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.287287  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-92801bf27615645d9ce40df12698fb63
I0824 21:04:15.287309  421580 addhandler.go:578] Pushed localPV device: blockdevice-92801bf27615645d9ce40df12698fb63 (/dev/sda) to etcd
I0824 21:04:15.288094  421580 uuid.go:73] device(/dev/sda1) is a partition, using partition UUID: fake-part-entry-1
I0824 21:04:15.288117  421580 uuid.go:101] generated uuid: blockdevice-59f4910ce3f1c54900704528c2ce63eb for device: /dev/sda1
E0824 21:04:15.288139  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-59f4910ce3f1c54900704528c2ce63eb" not found
I0824 21:04:15.288178  421580 uuid.go:73] device(/dev/sda) is a partition, using partition UUID: 
I0824 21:04:15.288186  421580 uuid.go:101] generated uuid: blockdevice-d41d8cd98f00b204e9800998ecf8427e for device: /dev/sda
E0824 21:04:15.288198  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-d41d8cd98f00b204e9800998ecf8427e" not found
I0824 21:04:15.288233  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-59f4910ce3f1c54900704528c2ce63eb
I0824 21:04:15.288410  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.288421  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
E0824 21:04:15.288434  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-299e74a12c1d4ac617cca4031b86088e" not found
I0824 21:04:15.288458  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-299e74a12c1d4ac617cca4031b86088e
I0824 21:04:15.288652  421580 addhandler.go:82] parent device of device: /dev/sda1 in use
I0824 21:04:15.288795  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.288805  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.288857  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-299e74a12c1d4ac617cca4031b86088e
I0824 21:04:15.288888  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-299e74a12c1d4ac617cca4031b86088e
I0824 21:04:15.289069  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.289080  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.289088  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.289093  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sda
I0824 21:04:15.289150  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-299e74a12c1d4ac617cca4031b86088e
I0824 21:04:15.289177  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-299e74a12c1d4ac617cca4031b86088e
I0824 21:04:15.289306  421580 uuid.go:73] device(/dev/sda1) is a partition, using partition UUID: fake-part-entry-1
I0824 21:04:15.289317  421580 uuid.go:101] generated uuid: blockdevice-59f4910ce3f1c54900704528c2ce63eb for device: /dev/sda1
E0824 21:04:15.289338  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-59f4910ce3f1c54900704528c2ce63eb" not found
I0824 21:04:15.289350  421580 uuid.go:73] device(/dev/sda) is a partition, using partition UUID: 
I0824 21:04:15.289358  421580 uuid.go:101] generated uuid: blockdevice-d41d8cd98f00b204e9800998ecf8427e for device: /dev/sda
E0824 21:04:15.289367  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-d41d8cd98f00b204e9800998ecf8427e" not found
I0824 21:04:15.289388  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-59f4910ce3f1c54900704528c2ce63eb
I0824 21:04:15.289593  421580 addhandler.go:82] parent device of device: /dev/sda1 in use
I0824 21:04:15.289697  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-123
I0824 21:04:15.289706  421580 addhandler.go:578] Pushed localPV device: blockdevice-123 () to etcd
I0824 21:04:15.289836  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.289844  421580 addhandler.go:578] Pushed localPV device: blockdevice-123 () to etcd
I0824 21:04:15.289980  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.289992  421580 addhandler.go:578] Pushed localPV device: blockdevice-123 () to etcd
I0824 21:04:15.290195  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-123
I0824 21:04:15.290208  421580 addhandler.go:594] Pushed cstor device: blockdevice-123 () to etcd
I0824 21:04:15.290340  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.290350  421580 addhandler.go:594] Pushed cstor device: blockdevice-123 () to etcd
I0824 21:04:15.290476  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.290485  421580 addhandler.go:594] Pushed cstor device: blockdevice-123 () to etcd
I0824 21:04:15.290660  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.290782  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-123
I0824 21:04:15.290905  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-123
I0824 21:04:15.291121  421580 customtagprobe.go:101] Device: /dev/sdb Label openebs.io/block-device-tag:label1 added by custom tag probe
I0824 21:04:15.291189  421580 customtagprobe.go:101] Device: /dev/sda Label openebs.io/block-device-tag:label1 added by custom tag probe
I0824 21:04:15.291274  421580 deletehandler.go:31] Disk /dev/sdb not in hierarchy
I0824 21:04:15.291332  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-wwn and Serial: fake-serial
I0824 21:04:15.291341  421580 uuid.go:101] generated uuid: blockdevice-4237c82d767e3233fa55f10dfa76f2c1 for device: /dev/sda
I0824 21:04:15.291348  421580 uuid.go:73] device(/dev/sda1) is a partition, using partition UUID: fake-part1
I0824 21:04:15.291354  421580 uuid.go:101] generated uuid: blockdevice-8b39130d1bc0f9715e41c65311560844 for device: /dev/sda1
I0824 21:04:15.291542  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-e56534a0813e85c645078aa63c6aa717
I0824 21:04:15.291716  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-wwn and Serial: fake-serial
I0824 21:04:15.291727  421580 uuid.go:101] generated uuid: blockdevice-4237c82d767e3233fa55f10dfa76f2c1 for device: /dev/sda
I0824 21:04:15.291742  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-bab5c524aebc1a7310f3d3c32e0807ff
I0824 21:04:15.291933  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-wwn and Serial: fake-serial
I0824 21:04:15.291944  421580 uuid.go:101] generated uuid: blockdevice-4237c82d767e3233fa55f10dfa76f2c1 for device: /dev/sda
I0824 21:04:15.291957  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-4237c82d767e3233fa55f10dfa76f2c1
I0824 21:04:15.292133  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-wwn and Serial: fake-serial
I0824 21:04:15.292143  421580 uuid.go:101] generated uuid: blockdevice-4237c82d767e3233fa55f10dfa76f2c1 for device: /dev/sda
I0824 21:04:15.292156  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-4237c82d767e3233fa55f10dfa76f2c1
I0824 21:04:15.292318  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-e56534a0813e85c645078aa63c6aa717
I0824 21:04:15.292484  421580 uuid.go:85] device(/dev/sdb) has a filesystem, using filesystem UUID: fake-fs-uuid
I0824 21:04:15.292495  421580 uuid.go:101] generated uuid: blockdevice-fa162d8841af6a7c1be3615bdd1e53f4 for device: /dev/sdb
I0824 21:04:15.292517  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-e56534a0813e85c645078aa63c6aa717
I0824 21:04:15.292730  421580 uuid.go:73] device(/dev/sda1) is a partition, using partition UUID: fake-part1
I0824 21:04:15.292741  421580 uuid.go:101] generated uuid: blockdevice-8b39130d1bc0f9715e41c65311560844 for device: /dev/sda1
I0824 21:04:15.292758  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-8b39130d1bc0f9715e41c65311560844
I0824 21:04:15.292922  421580 uuid.go:78] device(/dev/sda) has a WWN, using WWN: fake-wwn and Serial: fake-serial
I0824 21:04:15.292932  421580 uuid.go:101] generated uuid: blockdevice-4237c82d767e3233fa55f10dfa76f2c1 for device: /dev/sda
I0824 21:04:15.292951  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-e8eb82950af0664f282fab236f69d6ef
I0824 21:04:15.293095  421580 uuid.go:85] device(/dev/sda) has a filesystem, using filesystem UUID: fake-fs-uuid
I0824 21:04:15.293105  421580 uuid.go:101] generated uuid: blockdevice-fa162d8841af6a7c1be3615bdd1e53f4 for device: /dev/sda
I0824 21:04:15.293120  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-e56534a0813e85c645078aa63c6aa717
I0824 21:04:15.293210  421580 filter.go:68] configured filter1 : state enable
I0824 21:04:15.293222  421580 probe.go:89] configured probe1 : state enable
I0824 21:04:15.293294  421580 eventhandler.go:69] Processing details for /dev/sdX
I0824 21:04:15.293303  421580 probe.go:119] details filled by probe1
I0824 21:04:15.293311  421580 eventhandler.go:82] Processed details for /dev/sdX
I0824 21:04:15.293325  421580 uuid.go:78] device(/dev/sdX) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.293333  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sdX
E0824 21:04:15.293347  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-299e74a12c1d4ac617cca4031b86088e" not found
I0824 21:04:15.293374  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-299e74a12c1d4ac617cca4031b86088e
I0824 21:04:15.293381  421580 eventhandler.go:69] Processing details for /dev/sdZ
I0824 21:04:15.293388  421580 probe.go:119] details filled by probe1
I0824 21:04:15.293395  421580 filter.go:89] /dev/sdZ ignored by filter1
I0824 21:04:15.293497  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-299e74a12c1d4ac617cca4031b86088e
E0824 21:04:15.293512  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-7790348f6b96db34aa2a5e5f37b7cb2e" not found
I0824 21:04:15.293605  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-299e74a12c1d4ac617cca4031b86088e
I0824 21:04:15.293729  421580 uuid.go:78] device(/dev/sdX) has a WWN, using WWN: fake-WWN and Serial: fake-disk-serial
I0824 21:04:15.293739  421580 uuid.go:101] generated uuid: blockdevice-299e74a12c1d4ac617cca4031b86088e for device: /dev/sdX
I0824 21:04:15.293756  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-299e74a12c1d4ac617cca4031b86088e
I0824 21:04:15.293823  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-299e74a12c1d4ac617cca4031b86088e
E0824 21:04:15.293996  421580 mountprobe.go:127] mountIdentifier is found empty, mount probe will not fetch mount information.
I0824 21:04:15.294251  421580 mountprobe.go:134] no mount point found for /dev/sda5. clearing mount points if any
I0824 21:04:15.294766  421580 probe.go:89] configured probe-1 : state enable
I0824 21:04:15.294832  421580 probe.go:66] registering probes
I0824 21:04:15.294841  421580 probe.go:89] configured fake-probe : state enable
--- FAIL: TestFillDiskDetailsBySmart (0.00s)
    smartprobe_test.go:92: the device type is not supported yet, device type: "NVMe"
I0824 21:04:15.297122  421580 probe.go:89] configured udev probe : state enable
I0824 21:04:15.297185  421580 udevprobe.go:358] starting udev probe listener
E0824 21:04:15.298814  421580 udevprobe.go:235] could not get sysfs device for , err: unable to create sysfs device from devPath for device: , error: device name empty
E0824 21:04:15.298901  421580 udevprobe.go:235] could not get sysfs device for , err: unable to create sysfs device from devPath for device: , error: device name empty
E0824 21:04:15.298984  421580 udevprobe.go:235] could not get sysfs device for , err: unable to create sysfs device from devPath for device: , error: device name empty
E0824 21:04:15.299062  421580 udevprobe.go:235] could not get sysfs device for , err: unable to create sysfs device from devPath for device: , error: device name empty
E0824 21:04:15.299135  421580 udevprobe.go:235] could not get sysfs device for , err: unable to create sysfs device from devPath for device: , error: device name empty
I0824 21:04:15.299476  421580 udevprobe.go:245] Dependents of /dev/nvme0n1 : {Parent: Partitions:[] Holders:[/dev/dm-0 /dev/dm-1 /dev/dm-2] Slaves:[]}
I0824 21:04:15.299507  421580 udevprobe.go:255] Device: /dev/nvme0n1 is of type: disk
I0824 21:04:15.299794  421580 udevprobe.go:245] Dependents of /dev/nvme1n1 : {Parent: Partitions:[/dev/nvme1n1p1 /dev/nvme1n1p2] Holders:[] Slaves:[]}
I0824 21:04:15.299809  421580 udevprobe.go:255] Device: /dev/nvme1n1 is of type: disk
I0824 21:04:15.300049  421580 udevprobe.go:245] Dependents of /dev/nvme1n1p1 : {Parent:/dev/nvme1n1 Partitions:[] Holders:[] Slaves:[]}
I0824 21:04:15.300063  421580 udevprobe.go:255] Device: /dev/nvme1n1p1 is of type: partition
I0824 21:04:15.300335  421580 udevprobe.go:245] Dependents of /dev/nvme1n1p2 : {Parent:/dev/nvme1n1 Partitions:[] Holders:[] Slaves:[]}
I0824 21:04:15.300348  421580 udevprobe.go:255] Device: /dev/nvme1n1p2 is of type: partition
I0824 21:04:15.300641  421580 udevprobe.go:245] Dependents of /dev/nvme2n1 : {Parent: Partitions:[] Holders:[] Slaves:[]}
I0824 21:04:15.300653  421580 udevprobe.go:255] Device: /dev/nvme2n1 is of type: disk
I0824 21:04:15.300942  421580 udevprobe.go:245] Dependents of /dev/nvme3n1 : {Parent: Partitions:[] Holders:[] Slaves:[]}
I0824 21:04:15.300954  421580 udevprobe.go:255] Device: /dev/nvme3n1 is of type: disk
I0824 21:04:15.301266  421580 udevprobe.go:245] Dependents of /dev/nvme4n1 : {Parent: Partitions:[] Holders:[] Slaves:[]}
I0824 21:04:15.301279  421580 udevprobe.go:255] Device: /dev/nvme4n1 is of type: disk
I0824 21:04:15.301848  421580 udevprobe.go:245] Dependents of /dev/dm-0 : {Parent: Partitions:[] Holders:[] Slaves:[/dev/nvme0n1]}
I0824 21:04:15.301894  421580 udevprobe.go:255] Device: /dev/dm-0 is of type: lvm
I0824 21:04:15.302161  421580 udevprobe.go:245] Dependents of /dev/dm-1 : {Parent: Partitions:[] Holders:[] Slaves:[/dev/nvme0n1]}
I0824 21:04:15.302195  421580 udevprobe.go:255] Device: /dev/dm-1 is of type: lvm
I0824 21:04:15.302452  421580 udevprobe.go:245] Dependents of /dev/dm-2 : {Parent: Partitions:[] Holders:[] Slaves:[/dev/nvme0n1]}
I0824 21:04:15.302484  421580 udevprobe.go:255] Device: /dev/dm-2 is of type: lvm
E0824 21:04:15.302498  421580 sparsefilegenerator.go:188] Failed to read sparse file names : open : no such file or directory
I0824 21:04:15.302568  421580 filter.go:68] configured filter1 : state enable
I0824 21:04:15.302595  421580 eventhandler.go:69] Processing details for 
I0824 21:04:15.302734  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.302744  421580 eventhandler.go:82] Processed details for /dev/nvme1n1
I0824 21:04:15.302751  421580 uuid.go:78] device(/dev/nvme1n1) has a WWN, using WWN: eui.355a37304e9051370025384500000003 and Serial: S5Z7NE0N905137
I0824 21:04:15.302760  421580 uuid.go:101] generated uuid: blockdevice-6bea1b93e7eee385c02933c4a189313f for device: /dev/nvme1n1
E0824 21:04:15.302772  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-6bea1b93e7eee385c02933c4a189313f" not found
I0824 21:04:15.302817  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-6bea1b93e7eee385c02933c4a189313f
I0824 21:04:15.302824  421580 uuid.go:78] device(/dev/nvme1n1) has a WWN, using WWN: eui.355a37304e9051370025384500000003 and Serial: S5Z7NE0N905137
I0824 21:04:15.302830  421580 uuid.go:101] generated uuid: blockdevice-6bea1b93e7eee385c02933c4a189313f for device: /dev/nvme1n1
I0824 21:04:15.302847  421580 eventhandler.go:69] Processing details for 
E0824 21:04:15.302912  421580 udevprobe.go:278] /sys/dev/block/: : unable to create Udevice object for null struct struct_udev_device
I0824 21:04:15.302919  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-6bea1b93e7eee385c02933c4a189313f
I0824 21:04:15.302925  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.302944  421580 eventhandler.go:82] Processed details for 
I0824 21:04:15.302976  421580 uuid.go:78] device() has a WWN, using WWN: eui.355a37304e9051370025384500000003 and Serial: S5Z7NE0N905137
I0824 21:04:15.302990  421580 uuid.go:101] generated uuid: blockdevice-6bea1b93e7eee385c02933c4a189313f for device: 
I0824 21:04:15.303145  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-6bea1b93e7eee385c02933c4a189313f
I0824 21:04:15.303975  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-6bea1b93e7eee385c02933c4a189313f
I0824 21:04:15.304032  421580 eventhandler.go:69] Processing details for 
E0824 21:04:15.304062  421580 udevprobe.go:278] /sys/dev/block/: : unable to create Udevice object for null struct struct_udev_device
I0824 21:04:15.304119  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.304163  421580 eventhandler.go:82] Processed details for 
I0824 21:04:15.304186  421580 uuid.go:78] device() has a WWN, using WWN: eui.355a37304e7028730025384500000003 and Serial: S5Z7NE0N702873
I0824 21:04:15.304207  421580 uuid.go:101] generated uuid: blockdevice-7ee99599ec55535fe6bf11d02bd3aafe for device: 
E0824 21:04:15.304464  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-7ee99599ec55535fe6bf11d02bd3aafe" not found
I0824 21:04:15.304790  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-7ee99599ec55535fe6bf11d02bd3aafe
I0824 21:04:15.304825  421580 eventhandler.go:69] Processing details for 
E0824 21:04:15.304864  421580 udevprobe.go:278] /sys/dev/block/: : unable to create Udevice object for null struct struct_udev_device
I0824 21:04:15.304876  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.304889  421580 eventhandler.go:82] Processed details for 
I0824 21:04:15.304904  421580 uuid.go:78] device() has a WWN, using WWN: eui.355a37304e9051250025384500000003 and Serial: S5Z7NE0N905125
I0824 21:04:15.304918  421580 uuid.go:101] generated uuid: blockdevice-5e950fca65883a3424f7fcd2b151a133 for device: 
E0824 21:04:15.304947  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-5e950fca65883a3424f7fcd2b151a133" not found
I0824 21:04:15.304984  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-5e950fca65883a3424f7fcd2b151a133
I0824 21:04:15.304992  421580 eventhandler.go:69] Processing details for 
E0824 21:04:15.305010  421580 udevprobe.go:278] /sys/dev/block/: : unable to create Udevice object for null struct struct_udev_device
I0824 21:04:15.305018  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.305028  421580 eventhandler.go:82] Processed details for 
I0824 21:04:15.305037  421580 uuid.go:78] device() has a WWN, using WWN: eui.355a37304e7028710025384500000003 and Serial: S5Z7NE0N702871
I0824 21:04:15.305045  421580 uuid.go:101] generated uuid: blockdevice-d6b45836b01ada31db5d41cbf074d248 for device: 
E0824 21:04:15.305057  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-d6b45836b01ada31db5d41cbf074d248" not found
I0824 21:04:15.305078  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-d6b45836b01ada31db5d41cbf074d248
I0824 21:04:15.305085  421580 eventhandler.go:69] Processing details for 
E0824 21:04:15.305097  421580 udevprobe.go:278] /sys/dev/block/: : unable to create Udevice object for null struct struct_udev_device
I0824 21:04:15.305105  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.305113  421580 eventhandler.go:82] Processed details for 
I0824 21:04:15.305123  421580 uuid.go:78] device() has a WWN, using WWN: eui.355a37304e9051400025384500000003 and Serial: S5Z7NE0N905140
I0824 21:04:15.305130  421580 uuid.go:101] generated uuid: blockdevice-16b75c1c1ce581aee599739bd0ac728a for device: 
E0824 21:04:15.305145  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-16b75c1c1ce581aee599739bd0ac728a" not found
I0824 21:04:15.305168  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-16b75c1c1ce581aee599739bd0ac728a
I0824 21:04:15.305176  421580 eventhandler.go:69] Processing details for /dev/nvme0n1
I0824 21:04:15.305466  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.305480  421580 eventhandler.go:82] Processed details for /dev/nvme0n1
I0824 21:04:15.305489  421580 uuid.go:78] device(/dev/nvme0n1) has a WWN, using WWN: eui.355a37304e9051400025384500000003 and Serial: S5Z7NE0N905140
I0824 21:04:15.305500  421580 uuid.go:101] generated uuid: blockdevice-16b75c1c1ce581aee599739bd0ac728a for device: /dev/nvme0n1
I0824 21:04:15.305689  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-16b75c1c1ce581aee599739bd0ac728a
I0824 21:04:15.305817  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-16b75c1c1ce581aee599739bd0ac728a
I0824 21:04:15.305826  421580 eventhandler.go:69] Processing details for /dev/nvme1n1
I0824 21:04:15.306034  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.306046  421580 eventhandler.go:82] Processed details for /dev/nvme1n1
I0824 21:04:15.306055  421580 uuid.go:78] device(/dev/nvme1n1) has a WWN, using WWN: eui.355a37304e9051370025384500000003 and Serial: S5Z7NE0N905137
I0824 21:04:15.306064  421580 uuid.go:101] generated uuid: blockdevice-6bea1b93e7eee385c02933c4a189313f for device: /dev/nvme1n1
I0824 21:04:15.306155  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-6bea1b93e7eee385c02933c4a189313f
I0824 21:04:15.306263  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-6bea1b93e7eee385c02933c4a189313f
I0824 21:04:15.306272  421580 eventhandler.go:69] Processing details for /dev/nvme1n1p1
I0824 21:04:15.306506  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.306521  421580 eventhandler.go:82] Processed details for /dev/nvme1n1p1
I0824 21:04:15.306532  421580 uuid.go:73] device(/dev/nvme1n1p1) is a partition, using partition UUID: 9a1cce89-249d-43a7-ab93-d3787467d7a3
I0824 21:04:15.306542  421580 uuid.go:101] generated uuid: blockdevice-2d23a7f6f6418df7ac9cc78e3c18bdaa for device: /dev/nvme1n1p1
E0824 21:04:15.306555  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-2d23a7f6f6418df7ac9cc78e3c18bdaa" not found
I0824 21:04:15.306568  421580 uuid.go:78] device(/dev/nvme1n1) has a WWN, using WWN: eui.355a37304e9051370025384500000003 and Serial: S5Z7NE0N905137
I0824 21:04:15.306577  421580 uuid.go:101] generated uuid: blockdevice-6bea1b93e7eee385c02933c4a189313f for device: /dev/nvme1n1
I0824 21:04:15.306674  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-6bea1b93e7eee385c02933c4a189313f
I0824 21:04:15.306699  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-6bea1b93e7eee385c02933c4a189313f
I0824 21:04:15.306726  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-2d23a7f6f6418df7ac9cc78e3c18bdaa
I0824 21:04:15.306722  421580 features.go:149] Feature gate: PartitionTableUUID, state: enable
I0824 21:04:15.306735  421580 eventhandler.go:69] Processing details for /dev/nvme1n1p2
I0824 21:04:15.306743  421580 features.go:149] Feature gate: GPTBasedUUID, state: enable
I0824 21:04:15.306752  421580 features.go:149] Feature gate: APIService, state: disable
I0824 21:04:15.306760  421580 features.go:149] Feature gate: UseOSDisk, state: disable
I0824 21:04:15.306766  421580 features.go:149] Feature gate: ChangeDetection, state: disable
I0824 21:04:15.306837  421580 uuid.go:78] device() has a WWN, using WWN: 50E5495131BBB060892FBC8E and Serial: 
I0824 21:04:15.306847  421580 uuid.go:101] generated uuid: blockdevice-d3693a550a34eef92b71913c1f8a885b for device: 
I0824 21:04:15.306873  421580 uuid.go:73] device() is a partition, using partition UUID: 065e2357-05
I0824 21:04:15.306882  421580 uuid.go:101] generated uuid: blockdevice-c05df3f77dc0267b68bcd413c60bd458 for device: 
I0824 21:04:15.306907  421580 uuid.go:65] device() is a dm device, using DM UUID: CRYPT-LUKS1-f4608c76343d4b5badaf6651d32f752b-backup
I0824 21:04:15.306917  421580 uuid.go:101] generated uuid: blockdevice-156915fc39853b4e3fa1f6ded7c5b3e2 for device: 
I0824 21:04:15.306934  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.306943  421580 uuid.go:94] device() has a partition table, use partition table uuid: 6f479331-dad4-4ccb-b146-5c359c55399b
I0824 21:04:15.306947  421580 eventhandler.go:82] Processed details for /dev/nvme1n1p2
I0824 21:04:15.306953  421580 uuid.go:101] generated uuid: blockdevice-5965d9e18b1990cf6e7dfb180acd64bd for device: 
I0824 21:04:15.306960  421580 uuid.go:73] device(/dev/nvme1n1p2) is a partition, using partition UUID: b4277e6f-6223-497f-b648-2f0ddae660b3
I0824 21:04:15.306968  421580 uuid.go:101] generated uuid: blockdevice-904ac34518667e682044d38d4b7fba57 for device: /dev/nvme1n1p2
E0824 21:04:15.306983  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-904ac34518667e682044d38d4b7fba57" not found
I0824 21:04:15.306987  421580 uuid.go:78] device() has a WWN, using WWN: 50E5495131BBB060892FBC8E and Serial: 
I0824 21:04:15.306996  421580 uuid.go:78] device(/dev/nvme1n1) has a WWN, using WWN: eui.355a37304e9051370025384500000003 and Serial: S5Z7NE0N905137
I0824 21:04:15.306998  421580 uuid.go:101] generated uuid: blockdevice-d3693a550a34eef92b71913c1f8a885b for device: 
I0824 21:04:15.307007  421580 uuid.go:101] generated uuid: blockdevice-6bea1b93e7eee385c02933c4a189313f for device: /dev/nvme1n1
I0824 21:04:15.307043  421580 uuid.go:78] device() has a WWN, using WWN: 50E5495131BBB060892FBC8E and Serial: CT500MX500SSD1
I0824 21:04:15.307054  421580 uuid.go:101] generated uuid: blockdevice-955b23da63a54fc47abea653ae32a6a9 for device: 
I0824 21:04:15.307078  421580 uuid.go:85] device() has a filesystem, using filesystem UUID: 149108ca-f404-4556-a263-04943e6cb0b3
I0824 21:04:15.307087  421580 uuid.go:101] generated uuid: blockdevice-3c943e76f395b806e4db2d7b2870395c for device: 
I0824 21:04:15.307101  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-6bea1b93e7eee385c02933c4a189313f
I0824 21:04:15.307111  421580 uuid.go:65] device() is a dm device, using DM UUID: LVM-j2xmqvbcVWBQK9Jdttte3CyeVTGgxtVV5VcCi3nxdwihZDxSquMOBaGL5eymBNvk
I0824 21:04:15.307121  421580 uuid.go:101] generated uuid: blockdevice-fc0a9162dffbc2cfe843aee0b43e0b89 for device: 
I0824 21:04:15.307128  421580 blockdevicestore.go:131] eventcode=ndm.blockdevice.deactivate.success msg=Deactivated blockdevice rname=blockdevice-6bea1b93e7eee385c02933c4a189313f
I0824 21:04:15.307148  421580 uuid.go:60] device(/dev/loop98) is a loop device, using node name: brazos-mercury01 and path: /dev/loop98
I0824 21:04:15.307150  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-904ac34518667e682044d38d4b7fba57
I0824 21:04:15.307159  421580 uuid.go:101] generated uuid: blockdevice-c55c9852ae6c6ac524ab50743dd20867 for device: /dev/loop98
I0824 21:04:15.307162  421580 eventhandler.go:69] Processing details for /dev/nvme2n1
FAIL
I0824 21:04:15.307342  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.307354  421580 eventhandler.go:82] Processed details for /dev/nvme2n1
I0824 21:04:15.307364  421580 uuid.go:78] device(/dev/nvme2n1) has a WWN, using WWN: eui.355a37304e7028730025384500000003 and Serial: S5Z7NE0N702873
I0824 21:04:15.307373  421580 uuid.go:101] generated uuid: blockdevice-7ee99599ec55535fe6bf11d02bd3aafe for device: /dev/nvme2n1
I0824 21:04:15.307457  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-7ee99599ec55535fe6bf11d02bd3aafe
I0824 21:04:15.307568  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-7ee99599ec55535fe6bf11d02bd3aafe
I0824 21:04:15.307576  421580 eventhandler.go:69] Processing details for /dev/nvme3n1
I0824 21:04:15.307731  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.307742  421580 eventhandler.go:82] Processed details for /dev/nvme3n1
I0824 21:04:15.307752  421580 uuid.go:78] device(/dev/nvme3n1) has a WWN, using WWN: eui.355a37304e9051250025384500000003 and Serial: S5Z7NE0N905125
I0824 21:04:15.307761  421580 uuid.go:101] generated uuid: blockdevice-5e950fca65883a3424f7fcd2b151a133 for device: /dev/nvme3n1
I0824 21:04:15.307845  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-5e950fca65883a3424f7fcd2b151a133
I0824 21:04:15.307950  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-5e950fca65883a3424f7fcd2b151a133
I0824 21:04:15.307959  421580 eventhandler.go:69] Processing details for /dev/nvme4n1
I0824 21:04:15.308118  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.308129  421580 eventhandler.go:82] Processed details for /dev/nvme4n1
I0824 21:04:15.308140  421580 uuid.go:78] device(/dev/nvme4n1) has a WWN, using WWN: eui.355a37304e7028710025384500000003 and Serial: S5Z7NE0N702871
I0824 21:04:15.308149  421580 uuid.go:101] generated uuid: blockdevice-d6b45836b01ada31db5d41cbf074d248 for device: /dev/nvme4n1
I0824 21:04:15.308234  421580 blockdevicestore.go:146] Got blockdevice object : blockdevice-d6b45836b01ada31db5d41cbf074d248
I0824 21:04:15.308341  421580 blockdevicestore.go:113] eventcode=ndm.blockdevice.update.success msg=Updated blockdevice object rname=blockdevice-d6b45836b01ada31db5d41cbf074d248
I0824 21:04:15.308349  421580 eventhandler.go:69] Processing details for /dev/dm-0
I0824 21:04:15.308534  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.308550  421580 eventhandler.go:82] Processed details for /dev/dm-0
I0824 21:04:15.308560  421580 uuid.go:65] device(/dev/dm-0) is a dm device, using DM UUID: LVM-jkCtUKufysWupngzRCZ3j9zAFxN9hFwrJk1BKct21J3v0Wt30sS8JSCOfY5mPqjm
I0824 21:04:15.308570  421580 uuid.go:101] generated uuid: blockdevice-6e647ed936c9cbab00c8c5b29893c887 for device: /dev/dm-0
E0824 21:04:15.308583  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-6e647ed936c9cbab00c8c5b29893c887" not found
I0824 21:04:15.308609  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-6e647ed936c9cbab00c8c5b29893c887
I0824 21:04:15.308617  421580 eventhandler.go:69] Processing details for /dev/dm-1
I0824 21:04:15.308789  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.308801  421580 eventhandler.go:82] Processed details for /dev/dm-1
I0824 21:04:15.308811  421580 uuid.go:65] device(/dev/dm-1) is a dm device, using DM UUID: LVM-jkCtUKufysWupngzRCZ3j9zAFxN9hFwr4jMorYENZf77qBbn40t3jEr64KY5T62u
I0824 21:04:15.308820  421580 uuid.go:101] generated uuid: blockdevice-49a0014812e50d0e9fcf09366867921d for device: /dev/dm-1
E0824 21:04:15.308834  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-49a0014812e50d0e9fcf09366867921d" not found
I0824 21:04:15.308865  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-49a0014812e50d0e9fcf09366867921d
I0824 21:04:15.308873  421580 eventhandler.go:69] Processing details for /dev/dm-2
I0824 21:04:15.309032  421580 probe.go:119] details filled by udev probe
I0824 21:04:15.309042  421580 eventhandler.go:82] Processed details for /dev/dm-2
I0824 21:04:15.309051  421580 uuid.go:65] device(/dev/dm-2) is a dm device, using DM UUID: LVM-jkCtUKufysWupngzRCZ3j9zAFxN9hFwraH1QKM3Z9TI0tzywknV3iF7upKJMs5Px
I0824 21:04:15.309060  421580 uuid.go:101] generated uuid: blockdevice-b8c4d62c9dcdbfc58e661b278a41eb3c for device: /dev/dm-2
E0824 21:04:15.309074  421580 blockdevicestore.go:143] Unable to get blockdevice object : blockdevices.openebs.io "blockdevice-b8c4d62c9dcdbfc58e661b278a41eb3c" not found
I0824 21:04:15.309100  421580 blockdevicestore.go:45] eventcode=ndm.blockdevice.create.success msg=Created blockdevice object in etcd rname=blockdevice-b8c4d62c9dcdbfc58e661b278a41eb3c
coverage: 47.7% of statements
FAIL	github.com/openebs/node-disk-manager/cmd/ndm_daemonset/probe	0.056s
FAIL
ok  	github.com/openebs/node-disk-manager/db/kubernetes	0.022s	coverage: 29.3% of statements
?   	github.com/openebs/node-disk-manager/ndm-exporter	[no test files]
?   	github.com/openebs/node-disk-manager/ndm-exporter/collector	[no test files]
?   	github.com/openebs/node-disk-manager/pkg/blkid	[no test files]
?   	github.com/openebs/node-disk-manager/pkg/cleaner	[no test files]
ok  	github.com/openebs/node-disk-manager/pkg/controllers/blockdevice	0.026s	coverage: 16.7% of statements
ok  	github.com/openebs/node-disk-manager/pkg/controllers/blockdeviceclaim	0.029s	coverage: 48.0% of statements
?   	github.com/openebs/node-disk-manager/pkg/controllers/util	[no test files]
?   	github.com/openebs/node-disk-manager/pkg/crds	[no test files]
ok  	github.com/openebs/node-disk-manager/pkg/env	0.007s	coverage: 71.4% of statements
ok  	github.com/openebs/node-disk-manager/pkg/epoll	0.006s	coverage: 61.0% of statements
ok  	github.com/openebs/node-disk-manager/pkg/features	0.006s	coverage: 100.0% of statements
?   	github.com/openebs/node-disk-manager/pkg/logs	[no test files]
?   	github.com/openebs/node-disk-manager/pkg/metrics/smart	[no test files]
?   	github.com/openebs/node-disk-manager/pkg/metrics/static	[no test files]
ok  	github.com/openebs/node-disk-manager/pkg/mount	0.008s	coverage: 84.3% of statements
ok  	github.com/openebs/node-disk-manager/pkg/mount/libmount	0.004s	coverage: 45.7% of statements
ok  	github.com/openebs/node-disk-manager/pkg/partition	0.006s	coverage: 25.0% of statements
?   	github.com/openebs/node-disk-manager/pkg/seachest	[no test files]
ok  	github.com/openebs/node-disk-manager/pkg/select/blockdevice	0.022s	coverage: 21.0% of statements
?   	github.com/openebs/node-disk-manager/pkg/select/verify	[no test files]
ok  	github.com/openebs/node-disk-manager/pkg/server	0.006s	coverage: 85.7% of statements
?   	github.com/openebs/node-disk-manager/pkg/setup	[no test files]
ok  	github.com/openebs/node-disk-manager/pkg/smart	0.007s	coverage: 15.0% of statements
?   	github.com/openebs/node-disk-manager/pkg/spdk	[no test files]
ok  	github.com/openebs/node-disk-manager/pkg/sysfs	0.016s	coverage: 88.7% of statements
--- FAIL: TestGetUid (0.00s)
    --- FAIL: TestGetUid/check_for_os_disk_uuid (0.00s)
        common_test.go:174: 
            	Error Trace:	common_test.go:174
            	Error:      	Not equal: 
            	            	expected: "blockdevice-8544a81d0bc3e78a88bec332c3d33c8a"
            	            	actual  : "blockdevice-6bea1b93e7eee385c02933c4a189313f"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1 +1 @@
            	            	-blockdevice-8544a81d0bc3e78a88bec332c3d33c8a
            	            	+blockdevice-6bea1b93e7eee385c02933c4a189313f
            	Test:       	TestGetUid/check_for_os_disk_uuid
--- FAIL: TestGetPropertyValue (0.00s)
    device_test.go:41: 
        	Error Trace:	device_test.go:41
        	Error:      	Not equal: 
        	            	expected: "disk"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-disk
        	            	+
        	Test:       	TestGetPropertyValue
FAIL
coverage: 84.7% of statements
FAIL	github.com/openebs/node-disk-manager/pkg/udev	0.017s
FAIL
ok  	github.com/openebs/node-disk-manager/pkg/udevevent	0.006s	coverage: 33.3% of statements
?   	github.com/openebs/node-disk-manager/pkg/upgrade/v040_041	[no test files]
?   	github.com/openebs/node-disk-manager/pkg/upgrade/v041_042	[no test files]
ok  	github.com/openebs/node-disk-manager/pkg/util	0.008s	coverage: 87.3% of statements
?   	github.com/openebs/node-disk-manager/pkg/version	[no test files]
?   	github.com/openebs/node-disk-manager/spec/ndm	[no test files]
make: *** [Makefile:186: test] Error 1
```

**Comment by dborman-hpe** [comment]
So, https://github.com/openebs/node-disk-manager/blob/develop/api-service/node/services/listBlockDeviceDetails_test.go#L30-L33 is hardcoded to `/dev/sda`

Second, https://github.com/openebs/node-disk-manager/blob/683879d938b72464361e595171a9287d0f93fe4d/pkg/udev/mockdata.go#L117 is going to find the root disk, which in my case is an NVMe disk, and that leads to assumptions failing, like
```
    smartprobe_test.go:92: the device type is not supported yet, device type: "NVMe"
```

**Comment by akhilerm** [comment]
ok. got it. thank you.
