### PR TITLE
fix(tests): fix buggy tests in probe and sysfs

### LINKED ISSUE #589: TestUdevProbe fails with SIGSEGV in certain systems
[`TestUdevProbe`](https://github.com/openebs/node-disk-manager/blob/110066c2d6626ba26b55660b6e9a00294140b6be/cmd/ndm_daemonset/probe/udevprobe_test.go#L136) returns SIGSEGV after trying to create a GPT partition on a disk that is currently being used by the system.

Crash logs can be found in [this pastebin](https://pastebin.com/i9QNMdwG).

The issue seems to occur in cases when ndm isn't able to generate a uuid for the disk. The code for uuid generation can be found [here](https://github.com/openebs/node-disk-manager/blob/110066c2d6626ba26b55660b6e9a00294140b6be/cmd/ndm_daemonset/probe/uuid.go#L30). The failure in generating the uuid leads ndm to try creating a partition on the disk. This in turn fails since the device is busy and finally the test fails due to a nil pointer dereference on [this](https://github.com/openebs/node-disk-manager/blob/110066c2d6626ba26b55660b6e9a00294140b6be/cmd/ndm_daemonset/probe/udevprobe_test.go#L205) line.

**Environment**
- OS: Ubuntu 20.10 (Linux 5.8.0-50-generic, x86_64)
- Number of disks: 1 (with 4 partitions). **The disk does not have a wwn**.
- The machine is a VM running in VMWare Workstation.

### PR DESCRIPTION
**Pull request by z0marlin**
changes made:
- fix sysfs tests to cleanup after finishing. tests were failing when
run the second time after passing for the first time.
- skip `TestUdevProbe` in package probe if disk uuid cannot be
generated
- fix `TestFillDiskDetails` in package probe to correctly set
expected dev links

Signed-off-by: Aditya Jain <aditya.jainadityajain.jain@gmail.com>

**Checklist:**
- [x] Fixes #589 
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [x] Has the change log section been updated? 
- [x] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by z0marlin** [comment]
@akhilerm PTAL

File: pkg/sysfs/syspath_test.go [hunk 1]
```diff
@@ -17,10 +17,12 @@ limitations under the License.
 package sysfs
 
 import (
-	"github.com/openebs/node-disk-manager/blockdevice"
-	"github.com/stretchr/testify/assert"
 	"os"
+	"path/filepath"
 	"testing"
+
+	"github.com/openebs/node-disk-manager/blockdevice"
```
Comment (akhilerm) [inline pkg/sysfs/syspath_test.go:24]: :+1:

Comment (akhilerm) [reply pkg/sysfs/syspath_test.go:24]: Can we follow the "standard libraries - vendor - project", pattern for ordering imports.

File: pkg/sysfs/syspath_test.go [hunk 2]
```diff
@@ -76,20 +78,24 @@ func TestGetParent(t *testing.T) {
 }
 
 func TestGetDeviceSysPath(t *testing.T) {
-	sysFSDirectoryPath = "/tmp/sys/"
-
+	tmp := sysFSDirectoryPath
+	sysFSDirectoryPath = filepath.Join(t.TempDir(), "sys/") + "/"
+	t.Cleanup(func() {
+		sysFSDirectoryPath = tmp
```
Comment (akhilerm) [inline pkg/sysfs/syspath_test.go:84]: q: How will this work?

Comment (akhilerm) [reply pkg/sysfs/syspath_test.go:84]: When will this be executed. Also it sets the `sysFSDirectoryPath` back to the actual `/sys`

File: pkg/sysfs/syspath_test.go [hunk 3]
```diff
@@ -596,7 +647,8 @@ func TestSysFsDeviceGetDeviceType(t *testing.T) {
 			sysfsDevice: &Device{
 				deviceName: "sdb1",
 				path:       "/dev/sdb1",
-				sysPath:    "/tmp/sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sdb/sdb1/",
+				sysPath: filepath.Join(tmpDir,
+					"sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sdb/sdb1/") + "/",
```
Comment (akhilerm) [inline pkg/sysfs/syspath_test.go:651]:
```suggestion
					"sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sdb/sdb1") + "/",
```

Comment (akhilerm) [reply pkg/sysfs/syspath_test.go:651]: If using `filepath.Join()`, I dont think its necessary to mention that `/` at the end.

File: cmd/ndm_daemonset/probe/udevprobe_test.go [hunk 4]
```diff
@@ -186,8 +190,12 @@ func TestUdevProbe(t *testing.T) {
 	}
 	probeEvent.addBlockDeviceEvent(eventDetails)
 	// Retrieve disk resource
-	uuid, _ := generateUUID(*deviceDetails)
+	uuid, ok := generateUUID(*deviceDetails)
+	if !ok {
+		t.Skip("cannot uniquely identify disk. skipping")
```
Comment (akhilerm) [inline cmd/ndm_daemonset/probe/udevprobe_test.go:195]: Along with skipping this test, can you add another test case, in which the uuid will be generated and the blockdevice resource will be created. If we skip this test, I think there is no test available for `addBlockDeviceEvent`

**Review by akhilerm — COMMENTED** [review]
@z0marlin Provided some comments

**Comment by akhilerm** [comment]
@z0marlin Does the changes in this PR, fix the issue in #589 ?

File: pkg/sysfs/syspath_test.go (hunk 2 above)
Comment (z0marlin) [reply pkg/sysfs/syspath_test.go:84]: once the test is completed. just to reset the variable back to its value. It won't make any difference for now, but just added it in case not reverting back has some side effects in the future.

File: pkg/sysfs/syspath_test.go (hunk 3 above)
Comment (z0marlin) [reply pkg/sysfs/syspath_test.go:651]: you mean the `+ "/"` part?

File: cmd/ndm_daemonset/probe/udevprobe_test.go (hunk 4 above)
Comment (z0marlin) [reply cmd/ndm_daemonset/probe/udevprobe_test.go:195]: Sure. I'll have to see what test I can add and how I can make it work.

**Comment by z0marlin** [comment]
> @z0marlin Does the changes in this PR, fix the issue in #589 ?

Yes it does. Since the main issue was disk not being added because uuid couldn't be generated, we are skipping the test. Only in cases when the uuid isn't available, the pointer becomes `nil`

File: pkg/sysfs/syspath_test.go (hunk 1 above)
Comment (z0marlin) [reply pkg/sysfs/syspath_test.go:24]: My bad. will reorder

**Comment by z0marlin** [comment]
On further thought, I think we can also add nil-pointer checks and fail the test in such cases. These checks can be added after the uuid check so that we can be sure that a uuid was generated.

File: pkg/sysfs/syspath_test.go (hunk 3 above)
Comment (akhilerm) [reply pkg/sysfs/syspath_test.go:651]: nope. The `/` at the end of `block/sdb/sdb1/`

**Review by akhilerm — APPROVED** [review]
LGTM

**Comment by akhilerm** [comment]
@z0marlin Will the additional test for the skipped check be taken up in a different PR?

**Comment by z0marlin** [comment]
Alright, so If u see how I've rearranged the code, I think no additional test is needed. We aren't skipping the test. In case uuid is not generated, we expect the disk to not be added since the disk being used during tests is always the root disk. Hence, we just verify that the pointer is indeed nil. This according to me is a part of the test itself. So no additional test needed. Wdyt?

**Comment by akhilerm** [comment]
> Alright, so if you see how I've rearranged the code, I think no additional test is needed. We aren't skipping the test. In case uuid is not generated, we expect the disk to not be added since the disk being used during tests is always the root disk. Hence, we just verify that the pointer is indeed nil. This according to me is a part of the test itself. So no additional test needed. Wdyt?

Then its good. :+1:

**Review by RealHarshThakur — APPROVED** [review]
