### PR TITLE
style(ndm): fix lint errors in commands.go

### LINKED ISSUE #95: Fix lint errors in commands.go file
File: [commands.go](https://github.com/openebs/node-disk-manager/blob/master/cmd/app/command/commands.go)

```
Line 27: warning: comment on exported type NodeDiskManagerOptions should be of the form "NodeDiskManagerOptions ..." (with optional leading article) (golint)
Line 71: warning: comment on exported function RunNodeDiskManager should be of the form "RunNodeDiskManager ..." (golint)
```

### PR DESCRIPTION
**Pull request by nathan78906**
fixes #95 

fix lint errors

Signed-off-by: Nathan Seebarran <nathan.seebarran@gmail.com>

### CODE REVIEW

File: cmd/app/command/commands.go [hunk 1]
```diff
@@ -68,7 +68,7 @@ func NewNodeDiskManager() (*cobra.Command, error) {
 	return cmd, nil
 }
 
-// Run ndm
+// RunNodeDiskManager starts the node disk manager
```
Comment (shovanmaity) [inline cmd/app/command/commands.go]: can you change it like `RunNodeDiskManager starts ndm process`

Comment (nathan78906) [reply cmd/app/command/commands.go]: done :)
