### PR TITLE
style(ndm): Fixed linting error in cmd/controller/controller.go

### LINKED ISSUE #93: Fix lint error in controller.go
File: [controller.go](https://github.com/openebs/node-disk-manager/blob/master/cmd/controller/controller.go)

```
Line 35: warning: exported const NDMKind should have comment (or a comment on this block) or be unexported (golint)
Line 45: warning: exported const NDMDefaultDiskType should have comment (or a comment on this block) or be unexported (golint)
```

### PR DESCRIPTION
**Pull request by Rupeshiya**
Fixes #93
Signed-off-by: Rupesh Krishna Jha <rupeshiya@gmail.com>

### CODE REVIEW

**Comment by Rupeshiya** [comment]
@Akash4927  please review

File: cmd/controller/controller.go [hunk 1]
```diff
@@ -32,17 +32,25 @@ import (
...
 const (
-	NDMKind        = "Disk"                   // NDMKind is the CR kind.
-	NDMVersion     = "openebs.io/v1alpha1"    // NDMVersion is the CR version.
-	NDMHostKey     = "kubernetes.io/hostname" // NDMHostKey is host name label prefix.
-	NDMActive      = "Active"                 // NDMActive is constant for active resource status.
-	NDMInactive    = "Inactive"               // NDMInactive is constant for inactive resource status.
-	NDMUnknown     = "Unknown"                // NDMUnknown is constant for resource unknown satus.
-	NDMDiskTypeKey = "ndm.io/disk-type"       // NDMDiskTypeKey specifies the type of disk
+	// NDMKind is the CR kind.
+	NDMKind        = "Disk"
```
Comment (a4abhishek) [inline cmd/controller/controller.go]: Just run `go fmt cmd/controller/controller.go` and update the PR.

Comment (Rupeshiya) [reply cmd/controller/controller.go]: @a4abhishek  I am not familiar with go ,so can you tell me the steps to do so .

Comment (a4abhishek) [reply cmd/controller/controller.go]: Sure, we'll talk on slack.

File: cmd/controller/controller.go [hunk 2]
```diff
@@ -32,17 +32,25 @@ import (
...
+	NDMInactive = "Inactive"
+	// NDMUnknown is constant for resource unknown satus.
+	NDMUnknown = "Unknown"
+	// NDMDiskTypeKey specifies the type of disk
+	NDMDiskTypeKey = "ndm.io/disk-type"
 )
 
 const (
-	NDMDefaultDiskType = "disk" // NDMDefaultDiskType will be used to initialize the disk type
+	// NDMDefaultDiskType will be used to initialize the disk type
```
Comment (sonasingh46) [inline cmd/controller/controller.go]: If we can add a period at the end of comment that would be great.

File: cmd/controller/controller.go [hunk 3]
```diff
@@ -32,17 +32,25 @@ import (
...
+	// NDMHostKey is host name label prefix.
+	NDMHostKey = "kubernetes.io/hostname"
+	// NDMActive is constant for active resource status.
+	NDMActive = "Active"
+	// NDMInactive is constant for inactive resource status.
+	NDMInactive = "Inactive"
+	// NDMUnknown is constant for resource unknown satus.
+	NDMUnknown = "Unknown"
+	// NDMDiskTypeKey specifies the type of disk
+	NDMDiskTypeKey = "ndm.io/disk-type"
```
Comment (sonasingh46) [inline cmd/controller/controller.go]: If we can add a period at the end of comment that would be great.

Comment (Rupeshiya) [reply cmd/controller/controller.go]: done
