### PR TITLE
fix(os-disk-exclude-filter) Exclude multiple os disk paths

### LINKED ISSUE #224: Ability to exclude multiple os disks
Currently NDM can detect and exclude only a single os-disk. In cases where the user has configured his disks in the following manner
```
/       -   /dev/sda1
/var    -   /dev/sdb1
```
and os-disk-filter
```
- key:  os-disk-exclude-filter
        name: os disk exclude filter
        state: true
        exclude: "/,/var,/boot"
```
NDM should exclude both `sda` and `sdb`. In current behaviour NDM will exclude only `sda` and a device/disk CR will be created for `sdb`

**What is the expected behavior?**
If multiple disks are used as os-disks and given in configmap, all those disks should be excluded.

### PR DESCRIPTION
**Pull request by rahulchheda**
Signed-off-by: Rahul M Chheda <rchheda@infracloud.io>

## Pull Request template

**Why is this PR required? What issue does it fix?**:

**What this PR does?**:

**Does this PR require any upgrade changes?**:

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** : 
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Fixes #224 
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated? 
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track: 
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

### CODE REVIEW

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go [hunk 1]
```diff
@@ -90,7 +91,7 @@ func (odf *oSDiskExcludeFilter) Start() {
 		if devPath, err := mountPointUtil.GetDiskPath(); err != nil {
 			klog.Error(err)
 		} else {
-			odf.excludeDevPath = devPath
+			odf.excludeDevPath = append(odf.excludeDevPath, devPath)
 			return
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter.go:95]: Should not return here, since we may have multiple paths.

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go [hunk 2]
```diff
@@ -103,7 +104,7 @@ func (odf *oSDiskExcludeFilter) Start() {
...
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter.go:108]: Same comment as above. we should not return here as multiple paths may be present.

File: cmd/ndm_daemonset/filter/osdiskexcludefilter_test.go [hunk 3]
```diff
@@ -88,7 +98,16 @@ func TestOsDiskExcludeFilterExclude(t *testing.T) {
...
-			filter: oSDiskExcludeFilter{excludeDevPath: "/dev/sda"},
+			filter: oSDiskExcludeFilter{excludeDevPath: []string{"/dev/sda"}},
+			disk: &blockdevice.BlockDevice{
+				Identifier: blockdevice.Identifier{
+					DevPath: "/dev/sdaa",
+				},
+			},
+			expected: true,
+		},
+		"exclude path are /dev/sda, /dev/sdb and device path is /dev/sdba": {
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter_test.go:109]: `/dev/sdba` ?

File: cmd/ndm_daemonset/filter/osdiskexcludefilter_test.go [hunk 4]
```diff
@@ -70,16 +71,25 @@ func TestOsDiskExcludeFilterExclude(t *testing.T) {
...
 			disk: &blockdevice.BlockDevice{
 				Identifier: blockdevice.Identifier{
 					DevPath: "/dev/sda",
 				},
 			},
 			expected: false,
 		},
-		"exclude path is /dev/sda and  device path is /dev/sda1": {
-			filter: oSDiskExcludeFilter{excludeDevPath: "/dev/sda"},
+		"exclude path is /dev/sda and device path is /dev/sda1": {
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter_test.go:82]: Will it be possible to add new test cases, instead of modifying existing cases?

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go [hunk 5]
```diff
@@ -120,14 +121,19 @@ func (odf *oSDiskExcludeFilter) Exclude(blockDevice *blockdevice.BlockDevice) bo
 	// The partitionRegex is chosen depending on whether the device uses
 	// the p[0-9] partition naming structure or not.
 	var partitionRegex string
-	if util.IsMatchRegex(".+[0-9]+$", odf.excludeDevPath) {
-		// matches loop0, loop0p1, nvme3n0p1
-		partitionRegex = "(p[0-9]+)?$"
-	} else {
-		// matches sda, sda1
-		partitionRegex = "[0-9]*$"
+	for i := range odf.excludeDevPath {
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter.go:124]: :+1:

**Review by akhilerm — COMMENTED** [review]
@rahulchheda Given some comments.

File: cmd/ndm_daemonset/filter/osdiskexcludefilter_test.go (hunk 4 above)
Comment (rahulchheda) [reply cmd/ndm_daemonset/filter/osdiskexcludefilter_test.go:82]: @akhilerm seems like this is a new test case I added, can you hceck once more?

Comment (rahulchheda) [reply cmd/ndm_daemonset/filter/osdiskexcludefilter_test.go:82]: Older one's have to be modified to have slice rather than string

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go [hunk 6]
```diff
@@ -17,9 +17,10 @@ limitations under the License.
 package filter
 
 import (
-	"k8s.io/klog"
 	"strings"
 
+	"k8s.io/klog"
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter.go:22]: Can you keep the import statement such that vendored packages are the last section like [this](https://github.com/openebs/node-disk-manager/blob/503ec7fb835ee439687d39ab91599a63301a2233/cmd/ndm_daemonset/grpc/api.go#L19)

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go [hunk 7]
```diff
@@ -67,7 +68,7 @@ var oSDiskExcludeFilterRegister = func() {
 // oSDiskExcludeFilter controller and path of os disk
 type oSDiskExcludeFilter struct {
 	controller     *controller.Controller
-	excludeDevPath string
+	excludeDevPath []string
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter.go:71]:
```suggestion
	excludeDevPaths []string
```

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go [hunk 8]
```diff
@@ -120,14 +119,19 @@ func (odf *oSDiskExcludeFilter) Exclude(blockDevice *blockdevice.BlockDevice) bo
 	// The partitionRegex is chosen depending on whether the device uses
 	// the p[0-9] partition naming structure or not.
 	var partitionRegex string
-	if util.IsMatchRegex(".+[0-9]+$", odf.excludeDevPath) {
-		// matches loop0, loop0p1, nvme3n0p1
-		partitionRegex = "(p[0-9]+)?$"
-	} else {
-		// matches sda, sda1
-		partitionRegex = "[0-9]*$"
+	for i := range odf.excludeDevPath {
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter.go:122]:
```suggestion
	for excludeDevPath := range odf.excludeDevPaths {
```

File: cmd/ndm_daemonset/filter/osdiskexcludefilter_test.go [hunk 9]
```diff
@@ -17,10 +17,11 @@ limitations under the License.
 package filter
 
 import (
-	"github.com/openebs/node-disk-manager/blockdevice"
 	"sync"
 	"testing"
 
+	"github.com/openebs/node-disk-manager/blockdevice"
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter_test.go:23]: Same comment about ordering of imports.

**Review by akhilerm — COMMENTED** [review]
Some more nitpick comments on ordering of imports and variable names.

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go (hunk 8 above)
Comment (akhilerm) [reply cmd/ndm_daemonset/filter/osdiskexcludefilter.go]: @rahulchheda Can you take in this variable name change also.?

**Review by akhilerm — APPROVED** [review]
Changes are good. @rahulchheda Can you add a changelog file also.

**Review by akhilerm — APPROVED** [review]
LGTM

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go [hunk 10]
```diff
@@ -103,8 +103,7 @@ func (odf *oSDiskExcludeFilter) Start() {
 		if devPath, err := mountPointUtil.GetDiskPath(); err != nil {
 			klog.Error(err)
 		} else {
-			odf.excludeDevPath = devPath
-			return
+			odf.excludeDevPaths = append(odf.excludeDevPaths, devPath)
 		}
 	}
 	klog.Error("unable to apply os disk filter")
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter.go:109]: This message will be printed irrespective of whether the filter configuration succeeded or not. It should be printed only when the filter configuration fails.

**Review by akhilerm — CHANGES_REQUESTED** [review]
A small change is required on the log message.

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go [hunk 11]
```diff
@@ -88,10 +89,10 @@ func (odf *oSDiskExcludeFilter) Start() {
 	for _, mountPoint := range mountPoints {
 		mountPointUtil := mount.NewMountUtil(hostMountFilePath, "", mountPoint)
 		if devPath, err := mountPointUtil.GetDiskPath(); err != nil {
+			klog.Error("unable to apply os disk filter")
 			klog.Error(err)
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter.go:93]:
```suggestion
			klog.Errorf("unable to configure os disk filter for mountpoint: %s, error: %v", mountPoint, err)
```

File: cmd/ndm_daemonset/filter/osdiskexcludefilter.go [hunk 12]
```diff
@@ -101,33 +102,38 @@ func (odf *oSDiskExcludeFilter) Start() {
 	for _, mountPoint := range mountPoints {
 		mountPointUtil := mount.NewMountUtil(defaultMountFilePath, "", mountPoint)
 		if devPath, err := mountPointUtil.GetDiskPath(); err != nil {
+			klog.Error("unable to apply os disk filter")
 			klog.Error(err)
```
Comment (akhilerm) [inline cmd/ndm_daemonset/filter/osdiskexcludefilter.go:106]:
```suggestion
			klog.Errorf("unable to configure os disk filter for mountpoint: %s, error: %v", mountPoint, err)
```

**Review by akhilerm — APPROVED** [review]
/lgtm
